#!/bin/bash
set -euo pipefail

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

if [[ "${1:-}" == "--init" ]]; then
  shift
  pnpm local-development:init
else
  pnpm local-development:check
fi

exec pnpm dev:webpack -H localhost -p 3004 "$@"
