import { fileURLToPath } from "node:url";
import JSON5 from "json5";
import { configDefaults, defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [
    {
      // Mirror next.config's JSON5 rules so tests can render components over the data set.
      name: "magickli-json5",
      transform(code, id) {
        if (!id.endsWith(".json5")) return null;
        return {
          code: `export default ${JSON.stringify(JSON5.parse(code))};`,
          map: null,
        };
      },
    },
  ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      // The other tsconfig paths.
      "@magick-data": fileURLToPath(new URL("./data", import.meta.url)),
      "@magick-components": fileURLToPath(
        new URL("./src/components", import.meta.url),
      ),
      "next/font/local": fileURLToPath(
        new URL("./tests/nextFontLocal.ts", import.meta.url),
      ),
    },
  },
  test: {
    environment: "node",
    // The data tables are generated; a test file run on its own builds them.
    globalSetup: ["./data/build.mts"],
    // Agent sessions register git worktrees under .claude/, each a full
    // checkout whose test files this glob would otherwise collect and run.
    exclude: [...configDefaults.exclude, "output/**", ".claude/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "json-summary"],
      // Expand this list as domain logic is extracted from UI and persistence.
      include: [
        "src/doc/prepare.js",
        "src/doc/shortcuts.ts",
        "src/doc/access.ts",
        "src/doc/legacyAccess.ts",
        "src/doc/publications.ts",
        "src/doc/drafts.ts",
        "src/doc/gongoWrites.ts",
        "src/doc/sqlReads.ts",
        "src/doc/sqlRendered.ts",
        "src/doc/sqlWrites.ts",
        "src/doc/sqlPolicy.ts",
        "src/doc/compileContract.ts",
        "src/doc/publicShells.ts",
        "src/doc/publicRituals.ts",
        "src/study/scheduling.ts",
        "src/study/progressSnapshot.ts",
        "src/temples/create.ts",
        "src/offline/lease.ts",
        "src/offline/repository.ts",
        "src/offline/storage.ts",
        "src/offline/permissionContract.ts",
        "src/offline/sqlPermissionCheck.ts",
        "src/offline/lifecycle.ts",
        "src/offline/recovery.ts",
        "src/offline/ritualAssetInventory.ts",
        "src/offline/ritualAssetPlan.ts",
        "src/offline/ritualBundleManifest.ts",
        "src/offline/prepareRitualBundle.ts",
        "src/offline/ritualRenderDescriptor.ts",
        "src/offline/ritualBundlePublication.ts",
        "src/offline/ritualBundleRecords.ts",
        "src/offline/sqlRitualBundlePublications.ts",
        "src/offline/sqlRitualBundleReads.ts",
        "src/offline/r2RitualBundleStorage.ts",
        "src/offline/readRitualBundleAsset.ts",
        "src/files/ritualUploadProtocol.ts",
        "src/files/finalizeRitualUpload.ts",
        "src/files/validateRitualImage.ts",
        "src/files/ritualImageFrames.ts",
        "src/files/sqlRitualUploads.ts",
        "src/files/r2RitualStorage.ts",
        "src/files/staticRitualImageCatalog.ts",
        "src/files/legacyRitualImageCatalog.ts",
        "src/files/externalRitualImageCatalog.ts",
        "src/files/generatedRitualImageCatalog.ts",
        "src/files/ritualImageValidationIdentity.ts",
        "src/files/dataImage.ts",
        "src/files/validateRitualSvg.ts",
        "src/render/componentImageRequest.ts",
        "src/render/componentImageUrl.ts",
        "src/render/componentImage.tsx",
        "src/render/componentImageResponse.ts",
        "src/render/outlineTreeImage.ts",
        "src/render/registry.tsx",
        "src/render/contracts/index.ts",
        "src/render/contracts/types.ts",
        "src/render/contracts/treeOfLife.ts",
        "src/render/contracts/astroGeomancyChart.ts",
        "src/render/contracts/enochianTablet.ts",
        "src/render/contracts/sevenBranchedCandlestick.ts",
        "src/render/contracts/tableOfShewbread.ts",
        "src/render/contracts/roseSigil.ts",
        "src/export/svgExport.ts",
        "src/export/exportRuntime.ts",
        "src/export/ExportControls.tsx",
        "src/app/geomancy/reading/readingState.ts",
        "src/app/kabbalah/tree/treeSettings.ts",
        "src/lib/pageSearchParams.ts",
        "src/app/robots.ts",
        "src/app/sitemap.ts",
        "src/app/og/[[]...card]/route.tsx",
        "src/seo/cardArt.ts",
        "src/seo/cardList.ts",
        "src/seo/cards.ts",
        "src/seo/entities.ts",
        "src/seo/JsonLd.tsx",
        "src/seo/metadata.ts",
        "src/seo/pages.ts",
        "src/seo/site.ts",
        "src/components/gd/roseSigilGeometry.ts",
        "src/components/svgCoordinate.ts",
        "src/app/geomancy/tetragrams.ts",
        "data/assemble.ts",
        "data/integrity.ts",
        "data/schemas.ts",
        "data/kabbalah/seventyTwoAngelsDerived.ts",
        "src/app/chat/train/access.ts",
        "src/app/chat/train/ingestPdf.ts",
        "src/app/chat/train/upload/route.ts",
        "src/lib/ids.ts",
        "src/api-lib/gongoHttpAuth.ts",
        "src/auth/sqlAuth.ts",
        "src/db/legacyIds.ts",
        "src/migration/normalizeLegacyAuth.ts",
        "src/migration/classifyLegacyAuthSource.ts",
        "src/migration/decodeLegacyBson.ts",
        "src/migration/prepareLegacyBackup.ts",
        "src/migration/legacyImportRows.ts",
        "src/migration/legacyImportMigrations.ts",
        "src/migration/legacyImportCatalog.ts",
        "src/migration/sqlLegacyImport.ts",
        "src/migration/legacyImportConnection.ts",
        "src/migration/legacyImportCommand.ts",
        "src/migration/prepareLegacyImport.ts",
        "src/migration/legacyImportValue.ts",
        "src/migration/legacyImportCheckpoint.ts",
        "src/migration/planBetterAuthImport.ts",
        "src/migration/planLegacyDiscourseImport.ts",
        "src/migration/planLegacyMembershipImport.ts",
        "src/migration/planLegacyRitualImport.ts",
        "src/migration/planLegacyStudyImport.ts",
        "src/migration/planLegacyFileImport.ts",
        "src/schemas/templeMembership.ts",
        "src/app/chat/contracts.ts",
        "src/app/chat/conversation.ts",
        "src/app/chat/providers.ts",
        "src/app/chat/corpus.ts",
        "src/app/chat/mmr.ts",
        "src/app/chat/server.ts",
      ],
      thresholds: {
        perFile: true,
        statements: 95,
        branches: 90,
        functions: 95,
        lines: 95,
      },
    },
  },
});
