import { readFileSync, writeFileSync } from "node:fs";
import JSON5 from "json5";
import { bookPages } from "./bookPage";
import { readEvidence } from "./evidence";
import { handReadings, hebrewReadings } from "./hebrew";
import { plateEntries } from "./plateSource";
import { disagreements } from "./validate";

/**
 * The editorial apparatus: everywhere this edition departs from the book, or
 * cannot follow it.
 *
 * Lenain is published as he set it. Where he is wrong, the text keeps his
 * words and a note says what is wrong and what it should be; our own tables
 * use the corrected value. Where the scan cannot answer, the note says that
 * too, rather than the gap being quietly filled.
 *
 * It is built, not written. Which entries depart from his four tables is
 * arithmetic, and which Hebrew names two readings cannot agree on is a
 * comparison — asking a model to judge either would be the same mistake as
 * asking it whether a paragraph continues. `notes.json5` holds only what no
 * rule can see, each verified by hand against the page. See plan 031.
 */

const OUT_PATH = "data/kabbalah/lenain/apparatus.json5";
const HAND_NOTES = "scripts/seventyTwoAngels/notes.json5";

const HEADER = `// Generated by scripts/seventyTwoAngels/apparatus.ts. The notes that no rule
// can derive live in scripts/seventyTwoAngels/notes.json5 and are folded in
// here; everything else is computed from Lenain's own tables and from the two
// readings of his Hebrew. Do not hand-edit. See plan 031.
`;

export interface Note {
  /** The genius it concerns, or 0 for a note about the book at large. */
  no: number;
  kind: "correction" | "reading" | "reconstruction";
  /** Which field it applies to. Not a page: that is what `page` is for. */
  field: string;
  /**
   * The leaf it concerns, as that leaf's anchor — "p35", "p-IV". A note about
   * the book at large may still concern a page, and one that concerns none is
   * set in "About this edition" instead.
   *
   * It used to be smuggled into `field` as "p. 35", which is why the note
   * about the five revolutions reached no reader at all: it had no genius to
   * hang on, and nothing looked at `field` for a page.
   */
  page?: string;
  /** What the book prints, as it prints it. */
  printed: string;
  /** What this edition uses instead — empty where it uses nothing. */
  used: string;
  /** Why, in a sentence a reader can check. */
  why: string;
}

/** Notes only a person can make, each checked against the page by hand. */
function handNotes(): Note[] {
  return JSON5.parse(readFileSync(HAND_NOTES, "utf8"));
}

/** Where an entry departs from the tables the rest of the book keeps. */
function fromArithmetic(): Note[] {
  const notes: Note[] = [];
  const evidence = new Map(readEvidence().map((row) => [row.no, row]));
  for (const entry of plateEntries()) {
    const reading = evidence.get(entry.no);
    if (!reading) continue;
    for (const clash of disagreements({
      no: reading.no,
      scanned: reading.scanned,
    })) {
      notes.push({
        no: entry.no,
        kind: "correction",
        field: clash.field,
        printed: clash.scanned,
        used: clash.derived,
        why: "Lenain's own tables give otherwise, and the rest of the book keeps to them.",
      });
    }
  }
  return notes;
}

/** Where the heading's ordinal is not the entry's place in the sequence. */
function fromOrdinals(): Note[] {
  return plateEntries()
    .filter((entry) => entry.printedOrdinal !== undefined)
    .map((entry) => ({
      no: entry.no,
      kind: "correction" as const,
      field: "ordinal",
      printed: `${entry.printedOrdinal}e`,
      used: String(entry.no),
      why:
        `The entry stands between the ${entry.no - 1}th and the ` +
        `${entry.no + 1}th, and the first cabalistic table numbers it ` +
        `${entry.no}.`,
    }));
}

/** Where two readings of the Hebrew cannot be made to agree. */
function fromHebrew(): Note[] {
  const evidence = readEvidence();
  const { doubtful } = hebrewReadings(
    new Map(evidence.map((row) => [row.no, row.nameHe])),
    new Map(
      evidence.map((row) => [
        row.no,
        { hebrew: row.crop.he, legible: row.crop.legible },
      ]),
    ),
  );

  const byHand = handReadings();

  // Every name a person read gets a note, whether or not the machines still
  // disagree about it — the note records who read it, and that does not stop
  // being true when a later pass happens to match.
  const concerned = new Set([...doubtful.keys(), ...byHand.keys()]);

  return [...concerned]
    .sort((a, b) => a - b)
    .map((no) => {
      const reading = doubtful.get(no) ?? { crop: "", page: "", legible: true };
      const hand = byHand.get(no);
      const disagreed = reading.crop
        ? `Two readings of the scan differed — ${reading.crop} closer in, ` +
          `${reading.page || "nothing"} from the whole page.`
        : "Two readings of the scan could not settle this name.";

      if (!hand)
        return {
          no,
          kind: "reading" as const,
          field: "name.he",
          printed: reading.crop || reading.page || "",
          used: "",
          why: `${disagreed} No name is given rather than a guess between them.`,
        };

      return {
        no,
        kind: "reading" as const,
        field: "name.he",
        printed: hand.pointed,
        used: hand.plain,
        why:
          `${disagreed} Read from the scan by Gadi Cohen, who reads Hebrew. ` +
          `The dots sit above the letters, not within them.`,
      };
    });
}

/**
 * Every note that concerns a genius gets that genius's leaf, so the reading
 * side does not have to find the entry again. Doing it here is doing it once,
 * in the script that already cut the entries.
 */
function withLeaves(notes: Note[]): Note[] {
  const anchorOf = new Map<number, string>();
  const leafOf = new Map(
    plateEntries().map((entry) => [entry.no, entry.printedPages[0]]),
  );
  for (const page of bookPages())
    if (page.page.sequence === "body")
      anchorOf.set(page.page.number, page.page.anchor);

  return notes.map((note) => {
    if (note.page || !note.no) return note;
    const anchor = anchorOf.get(leafOf.get(note.no) ?? -1);
    return anchor ? { ...note, page: anchor } : note;
  });
}

function main() {
  const notes = withLeaves([
    ...handNotes(),
    ...fromOrdinals(),
    ...fromArithmetic(),
    ...fromHebrew(),
  ]).sort((a, b) => a.no - b.no || a.field.localeCompare(b.field));

  writeFileSync(OUT_PATH, `${HEADER}${JSON5.stringify(notes, null, 2)}\n`);

  const byKind = notes.reduce<Record<string, number>>((tally, note) => {
    tally[note.kind] = (tally[note.kind] ?? 0) + 1;
    return tally;
  }, {});
  console.log(
    `${notes.length} notes: ${Object.entries(byKind)
      .map(([kind, count]) => `${count} ${kind}`)
      .join(", ")}.`,
  );
  console.log(`  ${OUT_PATH}`);
}

if (process.argv[1]?.endsWith("apparatus.ts")) main();
