import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import JSON5 from "json5";
import { ANGEL_COUNT } from "../../data/kabbalah/seventyTwoAngelsDerived";
import { published, readExtraction, type StoredExtraction } from "./extract";
import { handReadings, hebrewReadings } from "./hebrew";
import { disagreements, hebrewProblems, shapeProblems } from "./validate";

/**
 * Turns the per-genius extractions into the three committed data files, and
 * reports every place the scan and Lenain's arithmetic disagree.
 *
 * The prose is split off by language because it is most of the bytes and the
 * page only wants it when a reader opens one, so it loads on demand.
 *
 *   pnpm exec tsx scripts/seventyTwoAngels/assemble.ts
 *   … --report   say what disagrees and write nothing
 */

const IN_DIR = "output/seventyTwoAngels";
const DATA_DIR = "data/kabbalah";
const TEXT_DIR = `${DATA_DIR}/seventyTwoAngelsText`;

const HEADER = `// Generated by scripts/seventyTwoAngels/assemble.ts from the OCR of
// Lazare Lenain, La Science Cabalistique (Amiens, 1823), which is public
// domain. The French is that scan repaired; the English is translated from
// the repaired French. Neither draws on any modern published translation.
// Everything Lenain's four tables make derivable — degrees, dates, hours,
// decade, planet, choir — lives in seventyTwoAngelsDerived.ts, not here.
// See plan 031.
`;

function pathFor(no: number) {
  return `${IN_DIR}/${String(no).padStart(2, "0")}.json`;
}

interface Correction {
  no: number;
  field: string;
  from: string;
  to: string;
  why: string;
}

const corrections: Correction[] = JSON5.parse(
  readFileSync(`${__dirname}/corrections.json5`, "utf8"),
);

/**
 * Applies the hand-verified corrections to one entry. Each `from` must appear
 * exactly once: a re-extraction that words the passage differently then fails
 * here rather than quietly dropping the correction on the floor.
 */
function correct(angel: StoredExtraction) {
  for (const fix of corrections.filter((c) => c.no === angel.no)) {
    const [head, tail] = fix.field.split(".");
    const fields = angel as unknown as Record<string, unknown>;
    const holder = (tail ? fields[head] : fields) as Record<string, string>;
    const key = tail ?? head;
    const occurrences = holder[key].split(fix.from).length - 1;
    if (occurrences !== 1)
      throw new Error(
        `Correction for ${angel.no} ${fix.field} matches ${occurrences} times, not once: "${fix.from}"`,
      );
    holder[key] = holder[key].replace(fix.from, fix.to);
  }
  return angel;
}

function read(no: number): StoredExtraction {
  return correct(readExtraction(no));
}

/** Only what the page shows; the prose and the `scanned` readings stay out. */
function record(angel: StoredExtraction) {
  return {
    no: angel.no,
    // The Hebrew is carried through where two independent readings of the page
    // agree on it, and left out where they do not. Lenain's Hebrew is small
    // and the scan is two centuries old; fifty-two names are corroborated and
    // the rest are held back rather than guessed at. See plan 031.
    name: hebrewFor(angel.no, angel.name.en),
    printedPages: angel.printedPages,
    attribute: angel.attribute,
    people: angel.people,
    godName: angel.godName,
    psalm: angel.psalm,
    invokedFor: angel.invokedFor,
    governs: angel.governs,
    bornUnder: angel.bornUnder,
    contrary: angel.contrary,
  };
}

function write(path: string, value: unknown) {
  writeFileSync(path, `${HEADER}${JSON5.stringify(value, null, 2)}\n`);
  const bytes = readFileSync(path).length;
  console.log(`${path} — ${(bytes / 1024).toFixed(1)} kB`);
}

let agreedHebrew = new Map<number, string>();
let byHand = new Map<number, { plain: string; pointed: string }>();

/**
 * A name read by a person outranks one two machines happened to agree on, and
 * the data says which it was. Lenain's dots are kept apart from the letters:
 * `he` identifies the name, `hePointed` is what he printed.
 */
function hebrewFor(no: number, en: string) {
  const hand = byHand.get(no);
  if (hand)
    return { en, he: hand.plain, hePointed: hand.pointed, heSource: "hand" };
  const agreed = agreedHebrew.get(no);
  if (agreed) return { en, he: agreed, heSource: "corroborated" };
  return { en };
}

function main() {
  const reportOnly = process.argv.includes("--report");
  // Reporting works on whatever has been extracted, so it is useful while a
  // run is still going; writing the data needs all seventy-two.
  const numbers = Array.from({ length: ANGEL_COUNT }, (_, i) => i + 1).filter(
    (no) => reportOnly === false || existsSync(pathFor(no)),
  );
  const angels = numbers.map(read);
  console.log(`${corrections.length} hand-verified corrections applied.`);
  if (reportOnly && angels.length < ANGEL_COUNT)
    console.log(`${angels.length} of ${ANGEL_COUNT} extracted so far.\n`);

  const readings = hebrewReadings(
    new Map(angels.map((angel) => [angel.no, angel.name.he])),
  );
  agreedHebrew = readings.agreed;
  byHand = handReadings();

  // Shape no longer decides what ships — two readings agreeing does — but a
  // corroborated name of an unexpected shape is worth saying out loud.
  const oddlyShaped = [...readings.agreed].filter(
    ([, he]) => hebrewProblems({ name: { en: "", he } }).length,
  );

  const clashes = angels.flatMap(disagreements);
  const shapes = angels.flatMap((angel) =>
    shapeProblems(angel).map((problem) => `${angel.no}: ${problem}`),
  );
  const unsure = angels.flatMap((angel) =>
    angel.uncertain.map((note) => `${angel.no}: ${note}`),
  );

  console.log(
    `${clashes.length} disagreements with the tables, ` +
      `${shapes.length} shape problems, ${readings.agreed.size} Hebrew names ` +
      `corroborated (${oddlyShaped.length} oddly shaped), ` +
      `${byHand.size} read by hand, ` +
      `${[...readings.doubtful.keys()].filter((no) => !byHand.has(no)).length} ` +
      `still held back, ` +
      `${unsure.length} notes.\n`,
  );
  for (const c of clashes)
    console.log(`  ${c.no} ${c.field}: scan "${c.scanned}" vs "${c.derived}"`);
  if (shapes.length) console.log(`\n${shapes.join("\n")}`);

  if (reportOnly) return;
  if (shapes.length)
    throw new Error("Shape problems must be resolved before writing the data");

  mkdirSync(TEXT_DIR, { recursive: true });
  write(`${DATA_DIR}/seventyTwoAngels.json5`, angels.map(record));
  // Lenain's notes go with his text. A reader who meets "(1)" in an entry has
  // to be able to read what it points at, and for five entries the call was
  // there while the note was held somewhere they would never see.
  // `published` is shared with the review, so what is judged and what is
  // shipped cannot drift apart.
  write(
    `${TEXT_DIR}/fr.json5`,
    angels.map((angel) => published(angel.french, angel.footnotesFr)),
  );
  write(
    `${TEXT_DIR}/en.json5`,
    angels.map((angel) =>
      published(
        angel.translation,
        angel.footnotes.map((note) => ({
          marker: note.marker,
          text: note.en,
        })),
      ),
    ),
  );
}

if (process.argv[1]?.endsWith("assemble.ts")) main();
