import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import JSON5 from "json5";
import { ANGEL_COUNT } from "../../data/kabbalah/seventyTwoAngelsDerived";
import { type AngelExtraction, angelExtraction } from "./schema";
import { disagreements, shapeProblems } from "./validate";

/**
 * Turns the per-genius extractions into the three committed data files, and
 * reports every place the scan and Lenain's arithmetic disagree.
 *
 * The prose is split off by language because it is most of the bytes and the
 * page only wants it when a reader opens one, so it loads on demand.
 *
 *   pnpm exec tsx scripts/seventyTwoAngels/assemble.ts
 *   … --report   say what disagrees and write nothing
 */

const IN_DIR = "output/seventyTwoAngels";
const DATA_DIR = "data/kabbalah";
const TEXT_DIR = `${DATA_DIR}/seventyTwoAngelsText`;

const HEADER = `// Generated by scripts/seventyTwoAngels/assemble.ts from the OCR of
// Lazare Lenain, La Science Cabalistique (Angers, 1823), which is public
// domain. The French is that scan repaired; the English is translated from
// the repaired French. Neither draws on any modern published translation.
// Everything Lenain's four tables make derivable — degrees, dates, hours,
// decade, planet, choir — lives in seventyTwoAngelsDerived.ts, not here.
// See plan 031.
`;

function read(no: number): AngelExtraction {
  const path = `${IN_DIR}/${String(no).padStart(2, "0")}.json`;
  return angelExtraction.parse(JSON.parse(readFileSync(path, "utf8")));
}

/** Only what the page shows; the prose and the `scanned` readings stay out. */
function record(angel: AngelExtraction) {
  return {
    no: angel.no,
    name: angel.name,
    attribute: angel.attribute,
    people: angel.people,
    godName: angel.godName,
    psalm: angel.psalm,
    invokedFor: angel.invokedFor,
    governs: angel.governs,
    bornUnder: angel.bornUnder,
    contrary: angel.contrary,
  };
}

function write(path: string, value: unknown) {
  writeFileSync(path, `${HEADER}${JSON5.stringify(value, null, 2)}\n`);
  const bytes = readFileSync(path).length;
  console.log(`${path} — ${(bytes / 1024).toFixed(1)} kB`);
}

function main() {
  const reportOnly = process.argv.includes("--report");
  const angels = Array.from({ length: ANGEL_COUNT }, (_, i) => read(i + 1));

  const clashes = angels.flatMap(disagreements);
  const shapes = angels.flatMap((angel) =>
    shapeProblems(angel).map((problem) => `${angel.no}: ${problem}`),
  );
  const unsure = angels.flatMap((angel) =>
    angel.uncertain.map((note) => `${angel.no}: ${note}`),
  );

  console.log(
    `${clashes.length} disagreements with the tables, ` +
      `${shapes.length} shape problems, ${unsure.length} notes.\n`,
  );
  for (const c of clashes)
    console.log(`  ${c.no} ${c.field}: scan "${c.scanned}" vs "${c.derived}"`);
  if (shapes.length) console.log(`\n${shapes.join("\n")}`);

  if (reportOnly) return;
  if (shapes.length)
    throw new Error("Shape problems must be resolved before writing the data");

  mkdirSync(TEXT_DIR, { recursive: true });
  write(`${DATA_DIR}/seventyTwoAngels.json5`, angels.map(record));
  for (const lang of ["en", "fr"] as const)
    write(
      `${TEXT_DIR}/${lang}.json5`,
      angels.map((angel) => angel.text[lang]),
    );
}

if (process.argv[1]?.endsWith("assemble.ts")) main();
