import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import JSON5 from "json5";
import { ANGEL_COUNT } from "../../data/kabbalah/seventyTwoAngelsDerived";
import { type AngelExtraction, angelExtraction } from "./schema";
import { disagreements, hebrewProblems, shapeProblems } from "./validate";

/**
 * Turns the per-genius extractions into the three committed data files, and
 * reports every place the scan and Lenain's arithmetic disagree.
 *
 * The prose is split off by language because it is most of the bytes and the
 * page only wants it when a reader opens one, so it loads on demand.
 *
 *   pnpm exec tsx scripts/seventyTwoAngels/assemble.ts
 *   … --report   say what disagrees and write nothing
 */

const IN_DIR = "output/seventyTwoAngels";
const DATA_DIR = "data/kabbalah";
const TEXT_DIR = `${DATA_DIR}/seventyTwoAngelsText`;

const HEADER = `// Generated by scripts/seventyTwoAngels/assemble.ts from the OCR of
// Lazare Lenain, La Science Cabalistique (Angers, 1823), which is public
// domain. The French is that scan repaired; the English is translated from
// the repaired French. Neither draws on any modern published translation.
// Everything Lenain's four tables make derivable — degrees, dates, hours,
// decade, planet, choir — lives in seventyTwoAngelsDerived.ts, not here.
// See plan 031.
`;

function pathFor(no: number) {
  return `${IN_DIR}/${String(no).padStart(2, "0")}.json`;
}

interface Correction {
  no: number;
  field: string;
  from: string;
  to: string;
  why: string;
}

const corrections: Correction[] = JSON5.parse(
  readFileSync(`${__dirname}/corrections.json5`, "utf8"),
);

/**
 * Applies the hand-verified corrections to one entry. Each `from` must appear
 * exactly once: a re-extraction that words the passage differently then fails
 * here rather than quietly dropping the correction on the floor.
 */
function correct(angel: AngelExtraction) {
  for (const fix of corrections.filter((c) => c.no === angel.no)) {
    const [head, tail] = fix.field.split(".");
    const fields = angel as unknown as Record<string, unknown>;
    const holder = (tail ? fields[head] : fields) as Record<string, string>;
    const key = tail ?? head;
    const occurrences = holder[key].split(fix.from).length - 1;
    if (occurrences !== 1)
      throw new Error(
        `Correction for ${angel.no} ${fix.field} matches ${occurrences} times, not once: "${fix.from}"`,
      );
    holder[key] = holder[key].replace(fix.from, fix.to);
  }
  return angel;
}

function read(no: number): AngelExtraction {
  return correct(
    angelExtraction.parse(JSON.parse(readFileSync(pathFor(no), "utf8"))),
  );
}

/** Only what the page shows; the prose and the `scanned` readings stay out. */
function record(angel: AngelExtraction) {
  return {
    no: angel.no,
    // The Hebrew is deliberately not carried through. It is the most damaged
    // part of the scan and the model reconstructs it differently every run —
    // 27 of 72 malformed on the last one, a different 27 each time, twice
    // returning the Tetragrammaton. A wrong name that is five letters ending
    // in אל passes every check we have, so the field is left unsourced rather
    // than filled with something that looks right. See plan 031.
    name: { en: angel.name.en },
    attribute: angel.attribute,
    people: angel.people,
    godName: angel.godName,
    psalm: angel.psalm,
    invokedFor: angel.invokedFor,
    governs: angel.governs,
    bornUnder: angel.bornUnder,
    contrary: angel.contrary,
  };
}

function write(path: string, value: unknown) {
  writeFileSync(path, `${HEADER}${JSON5.stringify(value, null, 2)}\n`);
  const bytes = readFileSync(path).length;
  console.log(`${path} — ${(bytes / 1024).toFixed(1)} kB`);
}

function main() {
  const reportOnly = process.argv.includes("--report");
  // Reporting works on whatever has been extracted, so it is useful while a
  // run is still going; writing the data needs all seventy-two.
  const numbers = Array.from({ length: ANGEL_COUNT }, (_, i) => i + 1).filter(
    (no) => reportOnly === false || existsSync(pathFor(no)),
  );
  const angels = numbers.map(read);
  console.log(`${corrections.length} hand-verified corrections applied.`);
  if (reportOnly && angels.length < ANGEL_COUNT)
    console.log(`${angels.length} of ${ANGEL_COUNT} extracted so far.\n`);

  const clashes = angels.flatMap(disagreements);
  const shapes = angels.flatMap((angel) =>
    shapeProblems(angel).map((problem) => `${angel.no}: ${problem}`),
  );
  const hebrew = angels.flatMap((angel) =>
    hebrewProblems(angel).map((problem) => `${angel.no}: ${problem}`),
  );
  const unsure = angels.flatMap((angel) =>
    angel.uncertain.map((note) => `${angel.no}: ${note}`),
  );

  console.log(
    `${clashes.length} disagreements with the tables, ` +
      `${shapes.length} shape problems, ${hebrew.length} Hebrew names ` +
      `unusable (not shipped), ${unsure.length} notes.\n`,
  );
  for (const c of clashes)
    console.log(`  ${c.no} ${c.field}: scan "${c.scanned}" vs "${c.derived}"`);
  if (shapes.length) console.log(`\n${shapes.join("\n")}`);

  if (reportOnly) return;
  if (shapes.length)
    throw new Error("Shape problems must be resolved before writing the data");

  mkdirSync(TEXT_DIR, { recursive: true });
  write(`${DATA_DIR}/seventyTwoAngels.json5`, angels.map(record));
  for (const lang of ["en", "fr"] as const)
    write(
      `${TEXT_DIR}/${lang}.json5`,
      angels.map((angel) => angel.text[lang]),
    );
}

if (process.argv[1]?.endsWith("assemble.ts")) main();
