import { readFileSync, writeFileSync } from "node:fs";
import JSON5 from "json5";
import type { AngelExtraction } from "./schema";

/**
 * What each entry says, as it says it — the half of the reading against which
 * Lenain's own tables are checked.
 *
 * Every correction note in the apparatus is derived from this: `validate.ts`
 * compares it against the arithmetic of his four tables and reports where the
 * entry departs from them. It lived only in `output/seventyTwoAngels/`, which
 * is gitignored, so the evidence for our editorial claims was the one part of
 * a scholarly edition that the repository did not hold, and that a reader
 * could not audit. It is committed now.
 *
 * It is deliberately not the translation. `scanned` is what the page prints,
 * uncorrected and unconverted — an invocation hour with "matin" or "soir" only
 * where that word is on the page, a planet named as the entry names it — so
 * the comparison has something to be a comparison with. The English and the
 * French live in `seventyTwoAngelsText/`; this is the reading behind them.
 *
 * Written by assemble.ts from the extractions, read by apparatus.ts. See
 * plan 033.
 */

const PATH = "data/kabbalah/lenain/evidence.json5";

const HEADER = `// What each of the seventy-two entries says, as printed: the reading the
// editorial apparatus is derived from, so that every correction can be checked
// against the page rather than taken on trust. Generated by
// scripts/seventyTwoAngels/assemble.ts from the extractions — see plan 033.
// Do not hand-edit.
`;

export interface AngelEvidence {
  no: number;
  /** The Hebrew as a machine read it from the whole page. */
  nameHe: string;
  /**
   * The same name read again from a close crop at 280 dpi. A name ships only
   * where these two agree, so both halves of that comparison are evidence and
   * both are committed.
   */
  crop: { he: string; legible: boolean };
  /** The readings as printed, for validate.ts to check against the tables. */
  scanned: AngelExtraction["scanned"];
  /** Whatever the reading was unsure of, in its own words. */
  uncertain: string[];
  /** Which model read it, so the data can say. */
  model: string;
}

export function writeEvidence(
  entries: (AngelExtraction & { model: string })[],
  crops: Map<number, { hebrew: string; legible: boolean }>,
) {
  const evidence: AngelEvidence[] = entries
    .map((entry) => ({
      no: entry.no,
      nameHe: entry.name.he,
      crop: {
        he: crops.get(entry.no)?.hebrew ?? "",
        legible: crops.get(entry.no)?.legible ?? false,
      },
      scanned: entry.scanned,
      uncertain: entry.uncertain,
      model: entry.model,
    }))
    .sort((a, b) => a.no - b.no);
  writeFileSync(PATH, `${HEADER}${JSON5.stringify(evidence, null, 2)}\n`);
  return { path: PATH, count: evidence.length };
}

export function readEvidence(): AngelEvidence[] {
  const evidence: AngelEvidence[] = JSON5.parse(readFileSync(PATH, "utf8"));
  if (!evidence.length) throw new Error(`No readings in ${PATH}`);
  return evidence;
}
