import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import JSON5 from "json5";
import { type BookPage, printedPageOf } from "./bookPage";
import { readPage } from "./transcribe";

/**
 * Gathers the per-page readings in `output/` into the one file the rest of the
 * work reads.
 *
 * This is the only script that touches `output/`, and it is run only after a
 * re-transcription. Everything downstream — the Markdown, the entries, the
 * apparatus — reads `pages.json5` instead, so the edition rebuilds from a
 * fresh clone.
 *
 * It did not, until now. The renderer, the entry cutter and the apparatus all
 * read `output/lenainPages/`, which is gitignored: 173 files and 740 KB of
 * vision transcription that cost real money, that nothing in the repository
 * could reproduce, and whose loss would have cost it again. Committing them
 * was never the answer — all 168 pages of `pages.json5` are byte-identical to
 * them, so the committed data already was the transcription and only the
 * scripts needed repointing. See plan 033.
 *
 *   pnpm exec tsx scripts/seventyTwoAngels/gatherPages.ts
 *   … --from 61 --to 113   leaves to gather, the whole volume by default
 *   … --out-dir output     where to write, for a partial run
 */

export const DATA_PATH = "data/kabbalah/lenain/pages.json5";

/**
 * Pages 1 to 6 of the PDF are the scan's own front matter — cover, library
 * plates, blanks, and Google's notice about the digitisation, which is theirs
 * and not Lenain's.
 */
export const VOLUME_FROM = 7;
export const VOLUME_TO = 174;

const HEADER = `// Lazare Lenain, La Science Cabalistique (Amiens, 1823), read from the
// Google Books scan page by page. Lenain died in 1877, so the text is public
// domain and no rights are asserted over it; the reading is CC BY 4.0 with the
// rest of data/. Generated by scripts/seventyTwoAngels/gatherPages.ts from the
// transcription in output/ — see plan 033. Do not hand-edit: re-read the page
// instead. This file is the source everything else reads.
`;

export function gather(from = VOLUME_FROM, to = VOLUME_TO): BookPage[] {
  const pages: BookPage[] = [];
  for (let pdfPage = from; pdfPage <= to; pdfPage++) {
    try {
      const transcription = readPage(pdfPage);
      pages.push({
        pdfPage: transcription.pdfPage,
        page: printedPageOf(transcription),
        blocks: transcription.blocks,
        uncertain: transcription.uncertain,
      });
    } catch {
      // A leaf not yet read is skipped, so a partial run still gathers.
    }
  }
  return pages;
}

function main() {
  const args = process.argv.slice(2);
  const value = (flag: string, fallback: number) => {
    const at = args.indexOf(flag);
    return at < 0 ? fallback : Number(args[at + 1]);
  };
  const outAt = args.indexOf("--out-dir");
  const outDir = outAt < 0 ? "" : `${args[outAt + 1]}/`;

  const pages = gather(value("--from", VOLUME_FROM), value("--to", VOLUME_TO));
  if (!pages.length) throw new Error("No pages have been read yet");

  const path = `${outDir}${DATA_PATH}`;
  if (!existsSync(dirname(path))) mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${HEADER}${JSON5.stringify(pages, null, 2)}\n`);

  const bySequence = pages.reduce<Record<string, number>>((tally, page) => {
    tally[page.page.sequence] = (tally[page.page.sequence] ?? 0) + 1;
    return tally;
  }, {});
  console.log(
    `${pages.length} leaves: ${Object.entries(bySequence)
      .map(([sequence, count]) => `${count} ${sequence}`)
      .join(", ")}.`,
  );
  console.log(`  ${path}`);
}

if (process.argv[1]?.endsWith("gatherPages.ts")) main();
