import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import JSON5 from "json5";
import type { PageBlock, PageTranscription } from "./pageSchema";
import { readPage } from "./transcribe";

/**
 * Gathers the per-page readings into one JSON5 file, and renders that to
 * Markdown.
 *
 * The JSON5 is what everything else reads: it keeps the page each block came
 * from, the footnotes apart from the prose they were printed under, and the
 * tables as tables. The Markdown is for people, and is generated — edit the
 * JSON5, or re-read the page, never the Markdown.
 *
 *   pnpm exec tsx scripts/seventyTwoAngels/renderPages.ts
 *   … --from 61 --to 113   pages to gather, the genii chapter by default
 *   … --out-dir output     where to write, for a partial run
 */

const DATA_PATH = "data/kabbalah/lenain/pages.json5";
const MARKDOWN_PATH = "public/docs/Lenain - La Science Cabalistique (1823).md";

const HEADER = `// Lazare Lenain, La Science Cabalistique (Angers, 1823), read from the
// Google Books scan page by page. Lenain died in 1832, so the text is public
// domain and no rights are asserted over it; the reading is CC BY 4.0 with the
// rest of data/. Generated by scripts/seventyTwoAngels/transcribe.ts — see
// plan 031. Do not hand-edit: re-read the page instead.
`;

const MARKDOWN_HEADER = `# La Science Cabalistique

**Lazare Lenain**, Angers, 1823. [Digitised by Google Books](https://www.google.co.uk/books/edition/La_science_cabalistique/ZqgpxTZ43HkC).

Lenain died in 1832, so this text is public domain and no rights are asserted
over it. This reading of it was made for [magick.ly](https://magick.ly) from the
scan, page by page, and is offered under
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) along with the rest of
the site's data. It replaces an earlier OCR, which could not read the Hebrew and
rendered many of the digits as letters.

Page numbers are Lenain's own. Footnotes are given under the page they were
printed on, as he set them.

`;

/** A table as Markdown, padded to its widest row so the columns line up. */
function table(rows: string[][]) {
  const width = Math.max(0, ...rows.map((row) => row.length));
  if (!width) return "";
  const cell = (value: string) => value.replace(/\|/g, "\\|").trim();
  const line = (row: string[]) =>
    `| ${Array.from({ length: width }, (_, i) => cell(row[i] ?? "")).join(" | ")} |`;

  // Lenain's tables carry no header row, so the first row is left as data and
  // the rule sits above it.
  return [
    `|${" |".repeat(width)}`,
    `|${" --- |".repeat(width)}`,
    ...rows.map(line),
  ].join("\n");
}

function blockToMarkdown(block: PageBlock) {
  if (block.kind === "furniture") return "";
  if (block.kind === "table") return table(block.rows);
  if (block.kind === "heading") return `## ${block.text}`;
  if (block.kind === "footnote")
    return `> ${block.text.replace(/\n/g, "\n> ")}`;
  return block.text;
}

function pageToMarkdown(page: PageTranscription) {
  const body = page.blocks.map(blockToMarkdown).filter(Boolean).join("\n\n");
  const number = page.printedPage > 0 ? `p. ${page.printedPage}` : "unnumbered";
  return `---\n\n<small>**[${number}]**</small>\n\n${body}`;
}

function main() {
  const args = process.argv.slice(2);
  const value = (flag: string, fallback: number) => {
    const at = args.indexOf(flag);
    return at < 0 ? fallback : Number(args[at + 1]);
  };
  const outAt = args.indexOf("--out-dir");
  const outDir = outAt < 0 ? "" : `${args[outAt + 1]}/`;
  const from = value("--from", 61);
  const to = value("--to", 113);

  const pages: PageTranscription[] = [];
  for (let page = from; page <= to; page++) {
    try {
      pages.push(readPage(page));
    } catch {
      // A page not yet read is skipped, so a partial run still renders.
    }
  }
  if (!pages.length) throw new Error("No pages have been read yet");

  const dataPath = `${outDir}${DATA_PATH}`;
  const markdownPath = `${outDir}${MARKDOWN_PATH}`;
  for (const path of [dataPath, markdownPath])
    if (!existsSync(dirname(path)))
      mkdirSync(dirname(path), { recursive: true });

  writeFileSync(dataPath, `${HEADER}${JSON5.stringify(pages, null, 2)}\n`);
  writeFileSync(
    markdownPath,
    `${MARKDOWN_HEADER}${pages.map(pageToMarkdown).join("\n\n")}\n`,
  );

  const blocks = pages.flatMap((page) => page.blocks);
  const hebrew = JSON.stringify(blocks).match(/[֐-׿]/g)?.length ?? 0;
  console.log(
    `${pages.length} pages, ${blocks.length} blocks, ` +
      `${blocks.filter((b) => b.kind === "table").length} tables, ` +
      `${blocks.filter((b) => b.kind === "footnote").length} footnotes, ` +
      `${hebrew} Hebrew letters.`,
  );
  console.log(`  ${dataPath}`);
  console.log(`  ${markdownPath}`);
}

if (process.argv[1]?.endsWith("renderPages.ts")) main();
