import type { ComponentImageRequest } from "../render/componentImageRequest";
import type { outlineTreeImage } from "../render/outlineTreeImage";
import type {
  StaticRitualRasterFacts,
  StaticRitualSvgFacts,
} from "./staticRitualImageCatalogTypes";

/** Records the actual renderer, bundled fonts and normalized request behind generated bytes. */
export interface GeneratedRitualImageProvenance {
  readonly referenceSha256: string;
  readonly sourceSha256: string;
  /** Only the Tree is a ritual reference; other registry slugs are never generated assets. */
  readonly request: ComponentImageRequest<"tree-of-life">;
  /**
   * The renderer, and since plan 032 step 3b the hash of the data the image
   * drew ([dataInputs.ts](../render/dataInputs.ts)) under its own version
   * string. Both are recorded verbatim, so the catalog's `sha256` — and the
   * plan's through it — moves when either half of an identity moves.
   */
  readonly renderer: Awaited<ReturnType<typeof outlineTreeImage>>["identity"];
}

/** Metadata only; raw source references remain with the selected ritual descriptor. */
export type GeneratedRitualImageEntry =
  | (Readonly<{ kind: "available"; sha256: string; bytes: number }> &
      GeneratedRitualImageProvenance &
      (StaticRitualRasterFacts | StaticRitualSvgFacts))
  | Readonly<{
      kind: "unresolved";
      referenceSha256: string;
      reason:
        | "unsupported-reference"
        | "unsupported-query"
        | "render-unavailable"
        | "render-mismatch"
        | "invalid-image"
        | "image-limit";
    }>;

/** Validated capture evidence; no authorization, durable publication or download readiness. */
export interface GeneratedRitualImageCatalogMetadata {
  /**
   * v1 still: the envelope keeps every key it had, in the same place, with the
   * same meaning. What 3b added sits inside `renderer`, which this catalog has
   * always copied verbatim and no reader keys on, and it carries a version
   * string of its own.
   */
  readonly profile: "magickli-generated-image-catalog-v1";
  readonly validationSha256: string;
  readonly sha256: string;
  readonly entries: readonly GeneratedRitualImageEntry[];
}

/** Trusted server capability. Returned byte copies survive disposal; retained bytes do not. */
export interface GeneratedRitualImageCatalog {
  readonly metadata: GeneratedRitualImageCatalogMetadata;
  copyBytes(referenceSha256: string): Uint8Array | null;
  dispose(): void;
}
